<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.542">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tips for Taxi Drivers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="STAT0006ICA1_23016751_files/libs/clipboard/clipboard.min.js"></script>
<script src="STAT0006ICA1_23016751_files/libs/quarto-html/quarto.js"></script>
<script src="STAT0006ICA1_23016751_files/libs/quarto-html/popper.min.js"></script>
<script src="STAT0006ICA1_23016751_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="STAT0006ICA1_23016751_files/libs/quarto-html/anchor.min.js"></script>
<link href="STAT0006ICA1_23016751_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="STAT0006ICA1_23016751_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="STAT0006ICA1_23016751_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="STAT0006ICA1_23016751_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="STAT0006ICA1_23016751_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tips for Taxi Drivers</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="explanatory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="explanatory-data-analysis-eda">Explanatory Data Analysis (EDA)</h2>
<p>A research has been conducted regarding the money taxi drivers receive in tip across different journeys. These journeys vary in the distance traveled, time duration, number of passengers, the time of day took place, taxi companies, and payment methods. Our goal is to investigate how these differences contribute to the amount of tips taxi drivers receive. The dataset contains 500 observations of 7 variables in total with no data missing.</p>
<p>The mean amount of tip taxi drivers receive in journeys is approximately 2.295 pounds, and the standard deviation is 1.124 pounds. We first analyze the relationships between our response variable <code>tip</code> and the three categorical covariates. The three boxplots shown below present the tip drivers receive when they work in different times of the day, for different companies, and pay through different payment methods. We can identify certain general patterns by observing these boxplots. In the first boxplot, it can be seen that drivers tend to receive more tips at night yet fewer tips in the morning. In the second boxplot, it can be identified that self-employed taxi drivers tend to receive slightly more tips than those drivers employed by the <code>Green_Taxis</code> and <code>Red_Taxis</code> companies. While in the last boxplot, we cannot yet identify the specific relationship between the tip drivers receive and the payment methods the passengers use as the three boxes are very close to each other. Therefore, further investigations will be required.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="STAT0006ICA1_23016751_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Now, we investigate the rest numeric covariates using scatterplots. The three scatterplots below demonstrate the relationships between the tip drivers receive and the mileage traveled during the taxi journey, the duration of the journey, and the number of passengers onboard. Observing the first and second scatterplots, the tips drivers receive increase as the taxi journey mileage and duration increase. Therefore, there appears to be a positive relationship between the tip amount and both the journey mileage and the trip duration. However, the third scatterplot is less informative and straightforward, indicating that further investigations may be required. But generally, there’s also a slight positive relationship between the tip amount and the number of passengers.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="STAT0006ICA1_23016751_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>In conclusion, our initial findings suggest that all the 6 covariates – including mileage, duration, the time of the day of the journey, payment methods, the company the drivers belong to, and the number of passengers – may all affect the amount of tip the drivers receive. All variables should therefore be considered when building the statistical model for the money drivers received in tip.</p>
<p><strong>Word count for Q1:</strong> (<strong>410</strong> / <strong>500</strong>).</p>
</section>
<section id="normality-check" class="level2">
<h2 class="anchored" data-anchor-id="normality-check">Normality Check</h2>
<ul>
<li>As can be seen from the normal QQ-plot below, the data points on the two sides show significant deviations from the 45-degree line; we therefore conclude that the variable <code>tip</code> is not normally distributed.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="STAT0006ICA1_23016751_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>By conducting a Shapiro-Wilk normality test, we get a p-value of 2.7142757^{-10} <span class="math inline">\(&lt; 0.05\)</span>, which implies that the distribution of the variable <code>tip</code> is significantly different from the normal distribution, we reject the normality.</li>
<li>The lack of normality in the response variable <code>tip</code> does not raise any concerns about fitting a normal linear model, as it is not required.</li>
</ul>
<p><strong>Word count for Q2:</strong> (<strong>92</strong> / <strong>150</strong>).</p>
</section>
<section id="linear-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-model">Linear Model</h2>
<p>The summary of the linear regression model for <code>tip</code> is shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.8002929</td>
<td style="text-align: right;">0.2207227</td>
<td style="text-align: right;">-8.1563574</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">mileage</td>
<td style="text-align: right;">0.0732290</td>
<td style="text-align: right;">0.0103362</td>
<td style="text-align: right;">7.0847258</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">duration</td>
<td style="text-align: right;">0.0771077</td>
<td style="text-align: right;">0.0109025</td>
<td style="text-align: right;">7.0724587</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">companyRed_Taxis</td>
<td style="text-align: right;">0.1597982</td>
<td style="text-align: right;">0.0763931</td>
<td style="text-align: right;">2.0917897</td>
<td style="text-align: right;">0.0369726</td>
</tr>
<tr class="odd">
<td style="text-align: left;">companySelf_Employed</td>
<td style="text-align: right;">0.3743610</td>
<td style="text-align: right;">0.0462175</td>
<td style="text-align: right;">8.0999845</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">passengers</td>
<td style="text-align: right;">0.2732211</td>
<td style="text-align: right;">0.0170396</td>
<td style="text-align: right;">16.0344435</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">timeevening</td>
<td style="text-align: right;">0.1715159</td>
<td style="text-align: right;">0.0668029</td>
<td style="text-align: right;">2.5674932</td>
<td style="text-align: right;">0.0105398</td>
</tr>
<tr class="even">
<td style="text-align: left;">timemorning</td>
<td style="text-align: right;">-0.0214697</td>
<td style="text-align: right;">0.0618470</td>
<td style="text-align: right;">-0.3471425</td>
<td style="text-align: right;">0.7286336</td>
</tr>
<tr class="odd">
<td style="text-align: left;">timenight</td>
<td style="text-align: right;">1.4327309</td>
<td style="text-align: right;">0.0598428</td>
<td style="text-align: right;">23.9415737</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">paymentcard</td>
<td style="text-align: right;">-0.2064597</td>
<td style="text-align: right;">0.0622158</td>
<td style="text-align: right;">-3.3184446</td>
<td style="text-align: right;">0.0009727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paymentcash</td>
<td style="text-align: right;">0.0842382</td>
<td style="text-align: right;">0.0795215</td>
<td style="text-align: right;">1.0593124</td>
<td style="text-align: right;">0.2899805</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We are not concerned about the negative intercept as it represents the expected tip a driver receives for the reference groups when all numerical variables are 0. In reality, such a taxi journey does not exist. Therefore, it is meaningless to interpret the intercept independently; we need to combine it with other aspects of the model to analyze them as a whole. Alternatively, it can be considered the “cost” of a taxi driving without passengers, which makes sense to be negative.</p>
<p><strong>Word count for Q3:</strong> (<strong>93</strong> / <strong>100</strong>).</p>
</section>
<section id="model-output-interpretations" class="level2">
<h2 class="anchored" data-anchor-id="model-output-interpretations">Model Output Interpretations</h2>
<ul>
<li><code>companySelf_employed</code>: The expected difference in the <code>tip</code> drivers receive between <code>Green_Taxis</code> drivers (reference category) and <code>Self_Employed</code> drivers is 0.3744 pounds, holding all other covariates fixed.</li>
<li><code>passengers</code>: The expected change in the <code>tip</code> drivers receive for a 1-person increase in <code>passengers</code> is 0.2732 pounds, holding all other covariates fixed.</li>
</ul>
<p><strong>Word count for Q4:</strong> (<strong>48</strong> / <strong>150</strong>).</p>
</section>
<section id="model-output-analysis" class="level2">
<h2 class="anchored" data-anchor-id="model-output-analysis">Model Output Analysis</h2>
<ul>
<li>The degree of freedom of the linear regression model can be calculated by <span class="math inline">\(\text{df} = n - p - 1,\)</span> where <span class="math inline">\(n\)</span> is the sample size, and <span class="math inline">\(p\)</span> represents the number of predictors. There are 5 levels of covariates by treating the covariate <code>passengers</code> as categorical, among which 1 level will be taken as the reference category, leaving only 4 levels as predictors. Compared to the previous <code>model1</code>, there are <span class="math inline">\(\Delta p = 4 - 1 = 3\)</span> more predictors, and therefore leading a decrease of <span class="math inline">\(3\)</span> degrees of freedom. Since the previous model has a degree of freedom of <span class="math inline">\(489\)</span>, the degree of freedom of <code>model2</code> would be <span class="math inline">\(486\)</span>.</li>
<li>The interpretation of the <code>passengers</code> covariate would now become the same as those of other categorical covariates. The interpretation of the estimated coefficients of <code>passengers</code> in the model would become the expected change in <code>tip</code> between the number of passengers onboard is 1 (reference group) and the number of passengers is more, holding all other covariates fixed.</li>
<li>No, the new model would not be nested in <code>model1</code> as it contains more covariates, whereas a nested model should contain a subset of the covariates of its full model.</li>
<li>I prefer handling the <code>passengers</code> covariate as a categorical data as it demonstrates a clearer relationship between the tip and the number of passengers.</li>
<li>No.&nbsp;The covariate <code>passengers</code> only takes 5 values and therefore is rather “discrete”, yet comparatively the other numeric covariates are more continuous and therefore cannot be treated as categorical.</li>
</ul>
<p><strong>Word count for Q5:</strong> (<strong>237</strong> / <strong>300</strong>).</p>
</section>
<section id="new-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="new-linear-model">New Linear Model</h2>
<ul>
<li><p>Since the driver’s claim involves both the distance traveled and the passage of time, we need to examine the level of dependence of the response variable <code>tip</code> to the change of the covariate <code>mileage</code> with different levels of <code>time</code>. Therefore, in the second model <code>model2</code>, we incorporate an interaction between the two covariates <code>mileage</code> and <code>time</code> to address the issue.</p></li>
<li><p>The model summary for <code>model2</code> is as shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.4558565</td>
<td style="text-align: right;">0.2246455</td>
<td style="text-align: right;">-6.4806837</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">mileage</td>
<td style="text-align: right;">0.0506237</td>
<td style="text-align: right;">0.0122057</td>
<td style="text-align: right;">4.1475495</td>
<td style="text-align: right;">0.0000397</td>
</tr>
<tr class="odd">
<td style="text-align: left;">timeevening</td>
<td style="text-align: right;">0.3248454</td>
<td style="text-align: right;">0.1602426</td>
<td style="text-align: right;">2.0272099</td>
<td style="text-align: right;">0.0431862</td>
</tr>
<tr class="even">
<td style="text-align: left;">timemorning</td>
<td style="text-align: right;">-0.0126079</td>
<td style="text-align: right;">0.1468299</td>
<td style="text-align: right;">-0.0858675</td>
<td style="text-align: right;">0.9316071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">timenight</td>
<td style="text-align: right;">0.4211566</td>
<td style="text-align: right;">0.1433290</td>
<td style="text-align: right;">2.9383913</td>
<td style="text-align: right;">0.0034561</td>
</tr>
<tr class="even">
<td style="text-align: left;">duration</td>
<td style="text-align: right;">0.0742611</td>
<td style="text-align: right;">0.0098453</td>
<td style="text-align: right;">7.5428272</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">companyRed_Taxis</td>
<td style="text-align: right;">0.1582887</td>
<td style="text-align: right;">0.0688851</td>
<td style="text-align: right;">2.2978650</td>
<td style="text-align: right;">0.0219934</td>
</tr>
<tr class="even">
<td style="text-align: left;">companySelf_Employed</td>
<td style="text-align: right;">0.4066611</td>
<td style="text-align: right;">0.0418211</td>
<td style="text-align: right;">9.7238364</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">passengers</td>
<td style="text-align: right;">0.2643579</td>
<td style="text-align: right;">0.0153757</td>
<td style="text-align: right;">17.1932617</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">paymentcard</td>
<td style="text-align: right;">-0.2130652</td>
<td style="text-align: right;">0.0561786</td>
<td style="text-align: right;">-3.7926428</td>
<td style="text-align: right;">0.0001678</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paymentcash</td>
<td style="text-align: right;">0.0382120</td>
<td style="text-align: right;">0.0718910</td>
<td style="text-align: right;">0.5315268</td>
<td style="text-align: right;">0.5952967</td>
</tr>
<tr class="even">
<td style="text-align: left;">mileage:timeevening</td>
<td style="text-align: right;">-0.0141387</td>
<td style="text-align: right;">0.0132389</td>
<td style="text-align: right;">-1.0679730</td>
<td style="text-align: right;">0.2860629</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mileage:timemorning</td>
<td style="text-align: right;">-0.0011588</td>
<td style="text-align: right;">0.0120783</td>
<td style="text-align: right;">-0.0959440</td>
<td style="text-align: right;">0.9236046</td>
</tr>
<tr class="even">
<td style="text-align: left;">mileage:timenight</td>
<td style="text-align: right;">0.0937530</td>
<td style="text-align: right;">0.0120426</td>
<td style="text-align: right;">7.7851143</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div></li>
<li><p>As can be seen from the model summary above, the coefficient of the reference category <code>mileage:timeafternoon</code> is <span class="math inline">\(0.051\)</span>; the coefficient of <code>mileage:timemorning</code> is <span class="math inline">\(0.051-0.001=0.05\)</span>; the coefficient of <code>mileage:timeevening</code> is <span class="math inline">\(0.051-0.014=0.037\)</span>; whereas the coefficient of <code>mileage:timenight</code> is <span class="math inline">\(0.051+0.094=0.145\)</span>. These positive coefficients represent how fast the tips increase with distance travelled in different time of the day. The driver’s claim is partly true since that the tips increase faster in the afternoon than in the morning, as well as faster at night than in the evening. However, it is also noticeable that there exists a gap between the afternoon and the evening when the increasing rate of tips actually slows down.</p></li>
<li><p>We implement the <code>anova()</code> function to carry out an F-test between the two models. The model summary is as shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">489</td>
<td style="text-align: right;">106.3309</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">486</td>
<td style="text-align: right;">85.7492</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">20.5817</td>
<td style="text-align: right;">38.88357</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div></li>
<li><p>We prefer the second model <code>model2</code> as the small p-value in the F-test in ANOVA suggests a significant difference between the two models, and the second model is a full model with a smaller Residual Sum of Squares (RSS).</p></li>
</ul>
<p><strong>Word count for Q6:</strong> (<strong>238</strong> / <strong>300</strong>).</p>
</section>
<section id="error-check" class="level2">
<h2 class="anchored" data-anchor-id="error-check">Error Check</h2>
<p><strong>Homoscedasticity of the errors</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="STAT0006ICA1_23016751_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>To check the homoscedasticity of the errors, we plot the standardized residuals against the fitted values. As can be seen from the plot above, the standardized residuals appear to be smaller for both smaller and larger fitted values, whereas appear to be larger for fitted values in the middle. Therefore, the plot provides certain evidence against homoscedasticity.</p>
<div style="page-break-after: always;"></div>
<p><strong>Normality of the errors</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="STAT0006ICA1_23016751_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>As can be seen from the QQ-plot of the standardized residuals above, all the data points roughly fall on the 45-degree reference line without significant deviations. Therefore, the normality assumption of errors is correct.</p>
<p><strong>Word count for Q7:</strong> (<strong>99</strong> / <strong>200</strong>).</p>
</section>
<section id="potential-model-improvement" class="level2">
<h2 class="anchored" data-anchor-id="potential-model-improvement">Potential Model Improvement</h2>
<p>Despite two possible improvements mentioned earlier – treating <code>passengers</code> covariate as categorical, and incorporating interactions between <code>mileage</code> and <code>time</code> of the day – there are some other approaches to potentially improve the model for <code>tip</code> further.</p>
<p>To begin with, since we observed a gap in the increment of the coefficients of the interactions of <code>mileage</code> and <code>time</code>, we can further break down <code>time</code> into more specific time period of the day. At present, the daytime is divided into morning, afternoon, and evening, while the entire night is treated as a single block. To address this, we could split the nighttime into two segments – early and late night – or even three by introducing a dusk period to complement the evening, which would balance the dispatch times more evenly.</p>
<p>Secondly, similar to the interaction implemented in <code>model2</code>, more interactions between covariates can be incorporated. For example, interactions between <code>payment</code> and <code>time</code> may have certain effects as it might be harder to hire a taxi at certain times of day – such as during the evening rush or or late at night – more people may opt to book and pay through an app.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 31%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.8842948</td>
<td style="text-align: right;">0.2353316</td>
<td style="text-align: right;">-8.0069785</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">paymentcard</td>
<td style="text-align: right;">-0.1366748</td>
<td style="text-align: right;">0.1149029</td>
<td style="text-align: right;">-1.1894807</td>
<td style="text-align: right;">0.2348349</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paymentcash</td>
<td style="text-align: right;">0.2289849</td>
<td style="text-align: right;">0.1941376</td>
<td style="text-align: right;">1.1794975</td>
<td style="text-align: right;">0.2387808</td>
</tr>
<tr class="even">
<td style="text-align: left;">timeevening</td>
<td style="text-align: right;">0.2479276</td>
<td style="text-align: right;">0.1644137</td>
<td style="text-align: right;">1.5079504</td>
<td style="text-align: right;">0.1322210</td>
</tr>
<tr class="odd">
<td style="text-align: left;">timemorning</td>
<td style="text-align: right;">0.0784073</td>
<td style="text-align: right;">0.1552336</td>
<td style="text-align: right;">0.5050924</td>
<td style="text-align: right;">0.6137243</td>
</tr>
<tr class="even">
<td style="text-align: left;">timenight</td>
<td style="text-align: right;">1.5219088</td>
<td style="text-align: right;">0.1519608</td>
<td style="text-align: right;">10.0151390</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mileage</td>
<td style="text-align: right;">0.0717190</td>
<td style="text-align: right;">0.0103888</td>
<td style="text-align: right;">6.9034941</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">companyRed_Taxis</td>
<td style="text-align: right;">0.1679433</td>
<td style="text-align: right;">0.0767258</td>
<td style="text-align: right;">2.1888775</td>
<td style="text-align: right;">0.0290838</td>
</tr>
<tr class="odd">
<td style="text-align: left;">companySelf_Employed</td>
<td style="text-align: right;">0.3752827</td>
<td style="text-align: right;">0.0468061</td>
<td style="text-align: right;">8.0178156</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">passengers</td>
<td style="text-align: right;">0.2737840</td>
<td style="text-align: right;">0.0170976</td>
<td style="text-align: right;">16.0130275</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">duration</td>
<td style="text-align: right;">0.0784730</td>
<td style="text-align: right;">0.0109775</td>
<td style="text-align: right;">7.1485247</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">paymentcard:timeevening</td>
<td style="text-align: right;">-0.0425996</td>
<td style="text-align: right;">0.1832302</td>
<td style="text-align: right;">-0.2324924</td>
<td style="text-align: right;">0.8162541</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paymentcash:timeevening</td>
<td style="text-align: right;">-0.3072854</td>
<td style="text-align: right;">0.2553695</td>
<td style="text-align: right;">-1.2032972</td>
<td style="text-align: right;">0.2294508</td>
</tr>
<tr class="even">
<td style="text-align: left;">paymentcard:timemorning</td>
<td style="text-align: right;">-0.1100570</td>
<td style="text-align: right;">0.1717539</td>
<td style="text-align: right;">-0.6407830</td>
<td style="text-align: right;">0.5219676</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paymentcash:timemorning</td>
<td style="text-align: right;">-0.2092240</td>
<td style="text-align: right;">0.2546747</td>
<td style="text-align: right;">-0.8215342</td>
<td style="text-align: right;">0.4117474</td>
</tr>
<tr class="even">
<td style="text-align: left;">paymentcard:timenight</td>
<td style="text-align: right;">-0.1247516</td>
<td style="text-align: right;">0.1669767</td>
<td style="text-align: right;">-0.7471196</td>
<td style="text-align: right;">0.4553549</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paymentcash:timenight</td>
<td style="text-align: right;">-0.0815021</td>
<td style="text-align: right;">0.2413785</td>
<td style="text-align: right;">-0.3376525</td>
<td style="text-align: right;">0.7357718</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Word count for Q8:</strong> (<strong>187</strong> / <strong>250</strong>).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>